version: "3.9"

services:
  database:
    image: postgres:9.5.4
    container_name: ignite_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres

  fin-backend:
    container_name: backend
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/
    ports:
      - 3333:3333
      - 9229:9229
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
